plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'com.jp.flowpay'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Flyway oficial
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'

	runtimeOnly 'org.postgresql:postgresql'

	// O starter-test JÁ INCLUI o @WebMvcTest, MockMvc, Mockito e JUnit
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
}

// Task padrão: Roda tudo EXCETO integração e E2E
tasks.named('test', Test) {
	useJUnitPlatform()
	filter {
		excludeTestsMatching "*.integration.*"
		excludeTestsMatching "*.e2e.*"
	}
}

// Nova task: Roda integração e E2E (requer banco de testes)
tasks.register('integrationTest', Test) {
	description = 'Roda testes de integração e E2E.'
	group = 'verification'

	testClassesDirs = sourceSets.test.output.classesDirs
	classpath = sourceSets.test.runtimeClasspath

	useJUnitPlatform()
	filter {
		includeTestsMatching "*.integration.*"
		includeTestsMatching "*.e2e.*"
	}
}