spring.application.name=API
spring.datasource.url=jdbc:postgresql://localhost:5433/flowpay_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.jdbc.core=DEBUG


flowpay.ticket.max-queue-size=3
flowpay.ticket.max-active-per-agent=3